import pool from "../config/database.js";

export async function findPortalSnapshot(gameId = null) {
  const gameParams = [gameId, gameId];
  const [stats, games, tournaments, results, players, teams, champions, content] = await Promise.all([
    pool.query(`SELECT (SELECT COUNT(*) FROM users) players, (SELECT COUNT(*) FROM teams WHERE ativo=1) teams, (SELECT COUNT(*) FROM tournaments) tournaments, (SELECT COUNT(*) FROM matches WHERE status='finalizada') matches, (SELECT COUNT(*) FROM matches WHERE status='andamento') live_matches, (SELECT COUNT(*) FROM tournaments WHERE status='aberto') open_tournaments, (SELECT COALESCE(SUM(CAST(REPLACE(REPLACE(premiacao,'R$',''),'.','') AS DECIMAL(14,2))),0) FROM tournaments) prize_pool`),
    pool.query(`SELECT g.*, COUNT(DISTINCT t.id) tournament_count, SUM(t.status='aberto') open_count, SUM(t.status='em_andamento') live_count FROM games g LEFT JOIN tournament_competition_settings tcs ON tcs.game_id=g.id LEFT JOIN tournaments t ON t.id=tcs.tournament_id WHERE g.ativo=1 GROUP BY g.id ORDER BY tournament_count DESC,g.nome`),
    pool.query(`SELECT t.*,g.nome game_name,g.nome_curto game_short_name,g.slug game_slug,tcs.format,tcs.best_of,COUNT(DISTINCT e.id) entry_count FROM tournaments t LEFT JOIN tournament_competition_settings tcs ON tcs.tournament_id=t.id LEFT JOIN games g ON g.id=COALESCE(tcs.game_id,CAST(t.game AS UNSIGNED)) LEFT JOIN entries e ON e.tournament_id=t.id AND e.status<>'cancelado' WHERE (? IS NULL OR g.id=?) GROUP BY t.id,g.id,tcs.tournament_id ORDER BY FIELD(t.status,'em_andamento','aberto','criado','fechado','finalizado','cancelado'),t.inicio LIMIT 12`, gameParams),
    pool.query(`SELECT m.id,m.tournament_id,m.round,m.score_team_a,m.score_team_b,m.finished_at,t.nome tournament_name,g.nome_curto game_short_name,ta.nome team_a,ta.logo team_a_logo,tb.nome team_b,tb.logo team_b_logo,w.nome winner FROM matches m INNER JOIN tournaments t ON t.id=m.tournament_id LEFT JOIN tournament_competition_settings tcs ON tcs.tournament_id=t.id LEFT JOIN games g ON g.id=COALESCE(tcs.game_id,CAST(t.game AS UNSIGNED)) INNER JOIN teams ta ON ta.id=m.team_a_id INNER JOIN teams tb ON tb.id=m.team_b_id LEFT JOIN teams w ON w.id=m.winner_team_id WHERE m.status='finalizada' AND (? IS NULL OR g.id=?) ORDER BY m.finished_at DESC LIMIT 12`, gameParams),
    pool.query(`SELECT u.id,u.nome,u.nickname,u.avatar,p.id player_id,p.nick,p.foto,t.id team_id,t.nome team_name,t.tag team_tag,g.id game_id,g.nome_curto game_short_name,COUNT(DISTINCT mps.match_id) matches,SUM(mps.kills) kills,SUM(mps.deaths) deaths,SUM(mps.assists) assists,SUM(mps.headshots) headshots,SUM(mps.mvp) mvps,SUM(m.winner_team_id=mps.team_id) wins FROM users u INNER JOIN players p ON p.user_id=u.id INNER JOIN teams t ON t.id=p.team_id INNER JOIN games g ON g.id=t.game_id LEFT JOIN match_player_stats mps ON mps.player_id=p.id LEFT JOIN matches m ON m.id=mps.match_id AND m.status='finalizada' WHERE p.status='ativo' AND (? IS NULL OR g.id=?) GROUP BY u.id,p.id,t.id,g.id ORDER BY kills DESC,mvps DESC LIMIT 10`, gameParams),
    pool.query(`SELECT t.id,t.nome,t.tag,t.slug,t.logo,t.banner,g.id game_id,g.nome_curto game_short_name,(SELECT COUNT(*) FROM team_members tm WHERE tm.team_id=t.id AND tm.status='ativo') members,(SELECT COUNT(*) FROM matches m WHERE (m.team_a_id=t.id OR m.team_b_id=t.id) AND m.status='finalizada') matches,(SELECT COUNT(*) FROM matches m WHERE m.winner_team_id=t.id AND m.status='finalizada') wins FROM teams t INNER JOIN games g ON g.id=t.game_id WHERE t.ativo=1 AND (? IS NULL OR g.id=?) ORDER BY wins DESC,matches DESC,t.nome LIMIT 10`, gameParams),
    pool.query(`SELECT t.id tournament_id,t.nome tournament_name,t.fim,w.id team_id,w.nome team_name,w.tag,w.logo,g.nome_curto game_short_name FROM tournaments t INNER JOIN matches m ON m.tournament_id=t.id AND m.status='finalizada' INNER JOIN teams w ON w.id=m.winner_team_id LEFT JOIN tournament_competition_settings tcs ON tcs.tournament_id=t.id LEFT JOIN games g ON g.id=COALESCE(tcs.game_id,CAST(t.game AS UNSIGNED)) WHERE t.status='finalizado' AND NOT EXISTS (SELECT 1 FROM matches newer WHERE newer.tournament_id=m.tournament_id AND newer.status='finalizada' AND (newer.round>m.round OR (newer.round=m.round AND newer.id>m.id))) AND (? IS NULL OR g.id=?) ORDER BY t.fim DESC LIMIT 8`, gameParams),
    pool.query(`SELECT * FROM public_content WHERE published=1 AND (published_at IS NULL OR published_at<=NOW()) ORDER BY type,sort_order,published_at DESC,id DESC`)
  ]);
  return { stats:stats[0][0], games:games[0], tournaments:tournaments[0], results:results[0], players:players[0], teams:teams[0], champions:champions[0], content:content[0] };
}

export async function searchPortal(query, gameId = null) {
  const term = `%${String(query || "").trim()}%`;
  const params = [term, gameId, gameId];
  const [tournaments, teams, players] = await Promise.all([
    pool.query(`SELECT 'torneio' type,t.id,t.nome title,t.descricao subtitle,CONCAT('/torneios/',t.id) url,g.nome_curto game FROM tournaments t LEFT JOIN tournament_competition_settings tcs ON tcs.tournament_id=t.id LEFT JOIN games g ON g.id=COALESCE(tcs.game_id,CAST(t.game AS UNSIGNED)) WHERE t.nome LIKE ? AND (? IS NULL OR g.id=?) ORDER BY t.inicio DESC LIMIT 8`, params),
    pool.query(`SELECT 'equipe' type,t.id,t.nome title,t.tag subtitle,CONCAT('/equipe/',t.slug) url,g.nome_curto game FROM teams t INNER JOIN games g ON g.id=t.game_id WHERE (t.nome LIKE ? OR t.tag LIKE ?) AND (? IS NULL OR g.id=?) ORDER BY t.nome LIMIT 8`, [term,term,gameId,gameId]),
    pool.query(`SELECT 'jogador' type,u.id,COALESCE(u.nickname,p.nick,u.nome) title,t.nome subtitle,CONCAT('/jogador/',COALESCE(NULLIF(u.nickname,''),u.id)) url,g.nome_curto game FROM users u INNER JOIN players p ON p.user_id=u.id INNER JOIN teams t ON t.id=p.team_id INNER JOIN games g ON g.id=t.game_id WHERE (u.nickname LIKE ? OR p.nick LIKE ? OR u.nome LIKE ?) AND (? IS NULL OR g.id=?) GROUP BY u.id,t.id,g.id ORDER BY title LIMIT 8`, [term,term,term,gameId,gameId])
  ]);
  return [...tournaments[0],...teams[0],...players[0]];
}

export async function findPublicTournamentCenter(tournamentId) {
  const [tournament, participants, matches, maps, matchMaps, mapPlayerStats, results] = await Promise.all([
    pool.query(`SELECT t.*,g.nome game_name,g.nome_curto game_short_name,g.slug game_slug,tcs.* FROM tournaments t LEFT JOIN tournament_competition_settings tcs ON tcs.tournament_id=t.id LEFT JOIN games g ON g.id=COALESCE(tcs.game_id,CAST(t.game AS UNSIGNED)) WHERE t.id=? LIMIT 1`, [tournamentId]),
    pool.query(`SELECT e.id entry_id,e.status,e.payment_status,tm.id team_id,tm.nome team_name,tm.tag,tm.logo FROM entries e INNER JOIN teams tm ON tm.id=e.team_id WHERE e.tournament_id=? AND e.status<>'cancelado' ORDER BY tm.nome`, [tournamentId]),
    pool.query(`SELECT m.*,ta.nome team_a,ta.logo team_a_logo,tb.nome team_b,tb.logo team_b_logo,w.nome winner,(SELECT gm.nome FROM match_maps mm LEFT JOIN game_maps gm ON gm.id=mm.game_map_id WHERE mm.match_id=m.id ORDER BY FIELD(mm.status,'andamento','pendente','finalizado'),mm.map_number LIMIT 1) current_map_name,(SELECT gm.imagem FROM match_maps mm LEFT JOIN game_maps gm ON gm.id=mm.game_map_id WHERE mm.match_id=m.id ORDER BY FIELD(mm.status,'andamento','pendente','finalizado'),mm.map_number LIMIT 1) current_map_image FROM matches m INNER JOIN teams ta ON ta.id=m.team_a_id INNER JOIN teams tb ON tb.id=m.team_b_id LEFT JOIN teams w ON w.id=m.winner_team_id WHERE m.tournament_id=? ORDER BY m.round,m.id`, [tournamentId]),
    pool.query(`SELECT gm.id,gm.nome,gm.slug,gm.imagem FROM tournament_map_pool tmp INNER JOIN game_maps gm ON gm.id=tmp.game_map_id WHERE tmp.tournament_id=? ORDER BY gm.ordem,gm.nome`, [tournamentId]),
    pool.query(`SELECT mm.id,mm.match_id,mm.map_number,mm.status,mm.score_team_a,mm.score_team_b,mm.winner_team_id,gm.nome map_name,gm.imagem map_image,w.nome winner FROM match_maps mm INNER JOIN matches m ON m.id=mm.match_id LEFT JOIN game_maps gm ON gm.id=mm.game_map_id LEFT JOIN teams w ON w.id=mm.winner_team_id WHERE m.tournament_id=? ORDER BY mm.match_id,mm.map_number`, [tournamentId]),
    pool.query(`SELECT mmps.id,mmps.match_map_id,mmps.match_id,mmps.player_id,mmps.team_id,mmps.kills,mmps.deaths,mmps.assists,mmps.headshots,mmps.mvp,p.nick,p.foto,t.nome team_name,t.logo team_logo FROM match_map_player_stats mmps INNER JOIN matches m ON m.id=mmps.match_id INNER JOIN players p ON p.id=mmps.player_id INNER JOIN teams t ON t.id=mmps.team_id WHERE m.tournament_id=? ORDER BY mmps.match_map_id,mmps.team_id,p.nick`, [tournamentId]),
    pool.query(`SELECT tr.*,c.nome champion_name,c.tag champion_tag,c.logo champion_logo,r.nome runner_up_name,r.tag runner_up_tag,r.logo runner_up_logo FROM tournament_results tr INNER JOIN teams c ON c.id=tr.champion_team_id LEFT JOIN teams r ON r.id=tr.runner_up_team_id WHERE tr.tournament_id=? LIMIT 1`, [tournamentId])
  ]);
  return { tournament:tournament[0][0] ?? null, participants:participants[0], matches:matches[0], map_pool:maps[0], match_maps:matchMaps[0], map_player_stats:mapPlayerStats[0].map((row) => ({ ...row, mvp:Boolean(row.mvp) })), result:results[0][0] ?? null };
}

export async function findPublicTeamProfile(slug) {
  const [[team]] = await pool.query(`SELECT t.id,t.nome,t.tag,t.slug,t.logo,t.banner,t.descricao,g.nome game_name,g.nome_curto game_short_name,(SELECT COUNT(*) FROM team_members tm WHERE tm.team_id=t.id AND tm.status='ativo') members,(SELECT COUNT(*) FROM matches m WHERE (m.team_a_id=t.id OR m.team_b_id=t.id) AND m.status='finalizada') matches,(SELECT COUNT(*) FROM matches m WHERE m.winner_team_id=t.id AND m.status='finalizada') wins FROM teams t INNER JOIN games g ON g.id=t.game_id WHERE t.slug=? AND t.ativo=1 LIMIT 1`, [slug]);
  if (!team) return null;
  const [titles] = await pool.query(`SELECT ttt.id,ttt.awarded_at,tr.runner_up_team_id,tr.final_match_id,t.id tournament_id,t.nome tournament_name,t.banner tournament_banner,g.nome_curto game_short_name FROM team_tournament_titles ttt INNER JOIN tournaments t ON t.id=ttt.tournament_id INNER JOIN games g ON g.id=ttt.game_id LEFT JOIN tournament_results tr ON tr.tournament_id=t.id WHERE ttt.team_id=? AND ttt.title_type='champion' ORDER BY ttt.awarded_at DESC`, [team.id]);
  return { team, titles };
}

export async function listPublicContentAdmin() { const [rows] = await pool.query(`SELECT * FROM public_content ORDER BY type,sort_order,id DESC`); return rows; }
export async function savePublicContentAdmin(id, userId, input) {
  if (id) { await pool.query(`UPDATE public_content SET type=?,title=?,subtitle=?,body=?,image_url=?,link_url=?,author_name=?,sort_order=?,published=?,published_at=? WHERE id=?`, [input.type,input.title,input.subtitle,input.body,input.image_url,input.link_url,input.author_name,input.sort_order,input.published?1:0,input.published_at,id]); return id; }
  const [result] = await pool.query(`INSERT INTO public_content (type,title,subtitle,body,image_url,link_url,author_name,sort_order,published,published_at,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?)`, [input.type,input.title,input.subtitle,input.body,input.image_url,input.link_url,input.author_name,input.sort_order,input.published?1:0,input.published_at,userId]); return Number(result.insertId);
}

export async function createContactMessage(input) { const [result]=await pool.query(`INSERT INTO public_contact_messages (name,email,subject,message) VALUES (?,?,?,?)`,[input.name,input.email,input.subject,input.message]); return Number(result.insertId); }
export async function listContactMessages() { const [rows]=await pool.query(`SELECT pcm.*,u.nome assigned_name FROM public_contact_messages pcm LEFT JOIN users u ON u.id=pcm.assigned_to ORDER BY FIELD(pcm.status,'novo','em_atendimento','respondido','arquivado'),pcm.created_at DESC`); return rows; }
export async function updateContactMessage(id,userId,input) { await pool.query(`UPDATE public_contact_messages SET status=?,assigned_to=?,admin_notes=? WHERE id=?`,[input.status,userId,input.admin_notes,id]); }
