import { deleteOfficialMatch, deleteOfficialTournament, getOfficialTournament, listOfficialTournaments, saveOfficialMatch, saveOfficialTournament } from "../models/officialTournament.model.js";
export const officialEvents=(admin=false)=>listOfficialTournaments(admin);
export async function officialEvent(id,admin=false){const data=await getOfficialTournament(id,admin);if(!data){const error=new Error("Campeonato oficial nao encontrado.");error.status=404;throw error;}return data;}
export async function upsertOfficialEvent(user,id,payload){const input=eventInput(payload);const saved=await saveOfficialTournament(id,input,user.id);return officialEvent(saved,true);}
export async function removeOfficialEvent(id){if(!await deleteOfficialTournament(id))throw new Error("Campeonato oficial nao encontrado.");return{message:"Campeonato oficial excluido."};}
export async function upsertOfficialResult(tournamentId,id,payload){await officialEvent(tournamentId,true);const input=matchInput(payload);const saved=await saveOfficialMatch(id,tournamentId,input);return(await officialEvent(tournamentId,true)).matches.find(item=>Number(item.id)===Number(saved));}
export async function removeOfficialResult(tournamentId,id){if(!await deleteOfficialMatch(tournamentId,id))throw new Error("Partida oficial nao encontrada.");return{message:"Partida excluida."};}
function eventInput(p){const name=req(p.name,"Informe o nome do campeonato.",180),organizer=req(p.organizer,"Informe a organizacao.",140),game_name=req(p.game_name,"Informe o jogo.",120);const status=["anunciado","em_andamento","finalizado","cancelado"].includes(p.status)?p.status:"anunciado";return{name,organizer,game_name,logo_url:opt(p.logo_url,500),banner_url:opt(p.banner_url,500),description:opt(p.description,10000),location:opt(p.location,180),prize_pool:opt(p.prize_pool,100),format_label:opt(p.format_label,120),official_url:opt(p.official_url,500),starts_at:date(p.starts_at),ends_at:date(p.ends_at),status,featured:p.featured===true,published:p.published!==false};}
function matchInput(p){const status=["agendada","ao_vivo","finalizada","cancelada"].includes(p.status)?p.status:"agendada";const a=numberOrNull(p.score_a),b=numberOrNull(p.score_b);return{stage_label:opt(p.stage_label,120),team_a:req(p.team_a,"Informe a equipe A.",140),team_a_logo:opt(p.team_a_logo,500),team_b:req(p.team_b,"Informe a equipe B.",140),team_b_logo:opt(p.team_b_logo,500),score_a:a,score_b:b,best_of:["bo1","bo3","bo5"].includes(p.best_of)?p.best_of:"bo3",map_summary:opt(p.map_summary,500),winner_name:status==="finalizada"?(a>b?p.team_a:b>a?p.team_b:opt(p.winner_name,140)):null,scheduled_at:date(p.scheduled_at),status,stream_url:opt(p.stream_url,500)};}
function req(v,m,n){const x=String(v||"").trim();if(!x)throw new Error(m);return x.slice(0,n);}function opt(v,n){const x=String(v||"").trim();return x?x.slice(0,n):null;}function date(v){return v?new Date(v):null;}function numberOrNull(v){return v===""||v===null||v===undefined?null:Math.max(0,Number(v));}
