import { Bell, CalendarDays, Check, ChevronRight, Crosshair, Gamepad2, LogOut, Medal, Search, Send, Shield, Swords, Trophy, UserRound, Users, X, XCircle } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { TeamPlayerRankingPanel } from "../../components/team/TeamPlayerRankingPanel";
import { Badge } from "../../components/ui/Badge";
import { Button } from "../../components/ui/Button";
import { Card, CardContent, CardHeader } from "../../components/ui/Card";
import { EmptyState } from "../../components/ui/EmptyState";
import { Input, Select } from "../../components/ui/Form";
import { Modal } from "../../components/ui/Modal";
import { StatCard } from "../../components/ui/StatCard";
import {
  cancelPlayerTeamRequest,
  leavePlayerWorkspaceTeam,
  requestPlayerTeam,
  respondPlayerInvite,
  searchPlayerTeams,
  updatePlayerGameProfile,
  updatePlayerWorkspaceProfile
} from "../../services/api";
import type { PlayerTeamSearchResult, PlayerWorkspaceGame, PlayerWorkspaceProfile } from "../../types/api";
import { Field, InlineEmpty, Metric, StatusBadge, Textarea, confirmAction, formatDate, formatDecimal, roleLabel, type PlayerModuleProps } from "./playerWorkspaceShared";

export function PlayerDashboardModule({ data }: PlayerModuleProps) {
  const next = data.matches.find((match) => match.status !== "finalizada");
  const pendingInvites = data.requests.filter((item) => item.tipo === "invite" && item.status === "pending");
  const latest = data.career.history.slice(0, 4);
  return <div className="space-y-5">
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <StatCard label="Nivel competitivo" value={String(data.career.level)} helper={`${data.career.xp} XP acumulados`} icon={<Trophy className="h-5 w-5" />} />
      <StatCard label="Ranking geral" value={data.career.totals.global_rank ? `#${data.career.totals.global_rank}` : "Sem posicao"} helper={`${data.career.totals.matches} partidas oficiais`} icon={<Medal className="h-5 w-5" />} />
      <StatCard label="K/D geral" value={formatDecimal(data.career.totals.kd)} helper={`${data.career.totals.kills} kills · ${data.career.totals.deaths} deaths`} icon={<Crosshair className="h-5 w-5" />} />
      <StatCard label="Convites pendentes" value={String(pendingInvites.length)} helper={pendingInvites.length ? "Aguardando sua resposta" : "Nenhum convite novo"} icon={<Users className="h-5 w-5" />} />
    </div>

    <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <Card><CardHeader><div className="flex items-center justify-between gap-3"><div><h2 className="font-display text-xl font-semibold">Proxima partida</h2><p className="mt-1 text-sm text-arena-muted">Sala, presenca e informacoes oficiais.</p></div>{next ? <StatusBadge value={next.status} /> : null}</div></CardHeader><CardContent>{next ? <div className="space-y-5"><div className="flex flex-col justify-between gap-4 border-b border-arena-line pb-5 sm:flex-row sm:items-center"><div><p className="text-xs font-semibold uppercase text-cyan-200">{next.tournament_name}</p><h3 className="mt-2 font-display text-3xl font-bold">vs {next.opponent}</h3><p className="mt-2 text-sm text-arena-muted">{formatDate(next.scheduled_at)} · {next.best_of.toUpperCase()}</p></div><div className="flex h-16 w-16 items-center justify-center border border-cyan-400/30 bg-cyan-400/10"><Swords className="h-7 w-7 text-cyan-200" /></div></div><div className="grid gap-3 sm:grid-cols-3"><Metric label="Mapas" value={next.maps || "A definir"} /><Metric label="Presenca" value={next.attendance_status ? String(next.attendance_status) : "Pendente"} /><Metric label="Lineup" value={next.in_official_lineup ? "Escalado" : "Acompanhando"} /></div><Link to="/jogador?module=matches"><Button className="w-full" icon={<ChevronRight className="h-4 w-4" />}>Abrir sala da partida</Button></Link></div> : <InlineEmpty text="Nenhuma partida agendada para sua equipe." />}</CardContent></Card>
      <Card><CardHeader><h2 className="font-display text-xl font-semibold">Minha equipe</h2></CardHeader><CardContent>{data.current_team ? <div className="space-y-4"><div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center border border-arena-line bg-white/[.04]">{data.current_team.team_logo ? <img alt="" className="h-full w-full object-cover" src={data.current_team.team_logo} /> : <Shield className="h-6 w-6 text-cyan-200" />}</div><div><h3 className="font-display text-xl font-semibold">{data.current_team.team_name}</h3><p className="text-sm text-arena-muted">{data.current_team.team_tag || "Sem tag"} · {data.current_team.game_name}</p></div></div><div className="grid grid-cols-2 gap-3"><Metric label="Elenco" value={String(data.members.length)} /><Metric label="Sua posicao" value={data.current_team.lineup_status === "titular" ? "Titular" : "Reserva"} /></div><div className="space-y-2">{data.team_ranking.players.slice(0, 3).map((player) => <div className="flex items-center justify-between border-b border-arena-line py-2" key={player.player_id}><span className="text-sm font-semibold">#{player.position} {player.nick}</span><span className="text-xs text-arena-muted">K/D {formatDecimal(player.kd)}</span></div>)}</div></div> : <EmptyState title="Voce esta sem equipe" description="Pesquise equipes abertas ou responda a um convite para iniciar sua jornada competitiva." />}</CardContent></Card>
    </div>

    <div className="grid gap-5 xl:grid-cols-2">
      <Card><CardHeader><h2 className="font-display text-xl font-semibold">Atividade recente</h2></CardHeader><CardContent className="space-y-3">{data.career.feed.slice(0, 6).map((item) => <div className="border-l-2 border-cyan-400 bg-white/[.03] p-3" key={item.id}><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-sm text-arena-muted">{item.description}</p><p className="mt-2 text-xs text-arena-muted">{formatDate(item.created_at)}</p></div>)}{!data.career.feed.length ? <InlineEmpty text="Sua linha do tempo comeca na primeira atividade oficial." /> : null}</CardContent></Card>
      <Card><CardHeader><h2 className="font-display text-xl font-semibold">Resultados e avisos</h2></CardHeader><CardContent className="space-y-4"><div className="space-y-2">{latest.map((match) => <div className="flex items-center justify-between border border-arena-line p-3" key={match.id}><div><p className="font-semibold">vs {match.opponent}</p><p className="text-xs text-arena-muted">{match.tournament_name} · {match.kills}/{match.deaths}/{match.assists}</p></div><Badge tone={match.won ? "success" : "danger"}>{match.won ? "Vitoria" : "Derrota"}</Badge></div>)}</div><div className="border-t border-arena-line pt-4">{data.notifications.slice(0, 4).map((item) => <div className="mb-3 flex gap-3" key={item.id}><Bell className="mt-0.5 h-4 w-4 shrink-0 text-cyan-200" /><div><p className="text-sm font-semibold">{item.titulo}</p><p className="text-xs text-arena-muted">{item.mensagem}</p></div></div>)}</div>{!latest.length && !data.notifications.length ? <InlineEmpty text="Nenhum resultado ou aviso recente." /> : null}</CardContent></Card>
    </div>
  </div>;
}

const linkFields = [
  ["steam", "Steam"], ["faceit", "FACEIT"], ["discord", "Discord"], ["riot_id", "Riot ID"], ["xbox", "Xbox"], ["playstation", "PlayStation"], ["epic_games", "Epic Games"], ["battlenet", "Battle.net"], ["twitch", "Twitch"], ["youtube", "YouTube"], ["kick", "Kick"], ["instagram", "Instagram"], ["x", "X"], ["tiktok", "TikTok"]
] as const;

export function PlayerProfileModule({ data, busy, run }: PlayerModuleProps) {
  const [form, setForm] = useState(() => profileForm(data.profile));
  const [gameForms, setGameForms] = useState<Record<number, ReturnType<typeof gameForm>>>(() => Object.fromEntries(data.games.map((game) => [game.game_id, gameForm(game)])));
  async function saveProfile() {
    await run("profile", () => updatePlayerWorkspaceProfile({ ...form, languages: form.languages.split(",").map((item) => item.trim()).filter(Boolean) }), "Perfil competitivo atualizado");
  }
  async function saveGame(game: PlayerWorkspaceGame) {
    const value = gameForms[game.game_id];
    await run(`game-${game.game_id}`, () => updatePlayerGameProfile(game.game_id, value), `${game.nome} vinculado ao perfil`);
  }
  return <div className="space-y-5">
    <Card><div className="relative h-44 overflow-hidden border-b border-arena-line bg-[linear-gradient(120deg,#071b2a,#161329)]">{form.banner ? <img alt="Banner do perfil" className="h-full w-full object-cover" src={form.banner} /> : null}<div className="absolute inset-x-0 bottom-0 flex items-end gap-4 bg-gradient-to-t from-black/80 to-transparent p-5"><div className="flex h-20 w-20 shrink-0 items-center justify-center overflow-hidden border-2 border-cyan-300 bg-arena-panel">{form.avatar ? <img alt="Avatar" className="h-full w-full object-cover" src={form.avatar} /> : <UserRound className="h-8 w-8 text-cyan-200" />}</div><div><h2 className="font-display text-2xl font-bold">{form.nickname || data.profile.nome}</h2><p className="text-sm text-arena-muted">Nivel {data.career.level} · {data.career.totals.matches} partidas</p></div></div></div><CardContent className="space-y-5 pt-5"><div className="grid gap-4 md:grid-cols-2"><Field label="Nickname"><Input value={form.nickname} onChange={(event) => setForm({ ...form, nickname: event.target.value })} /></Field><Field label="Nome"><Input value={form.nome} onChange={(event) => setForm({ ...form, nome: event.target.value })} /></Field><Field label="Avatar (URL)"><Input value={form.avatar} onChange={(event) => setForm({ ...form, avatar: event.target.value })} /></Field><Field label="Banner (URL)"><Input value={form.banner} onChange={(event) => setForm({ ...form, banner: event.target.value })} /></Field><Field label="Cidade"><Input value={form.cidade} onChange={(event) => setForm({ ...form, cidade: event.target.value })} /></Field><Field label="Estado"><Input value={form.estado} onChange={(event) => setForm({ ...form, estado: event.target.value })} /></Field><Field label="Pais"><Input value={form.pais} onChange={(event) => setForm({ ...form, pais: event.target.value })} /></Field><Field label="Data de nascimento (opcional)"><Input type="date" value={form.birth_date} onChange={(event) => setForm({ ...form, birth_date: event.target.value })} /></Field><Field label="Idiomas (separados por virgula)"><Input value={form.languages} onChange={(event) => setForm({ ...form, languages: event.target.value })} /></Field></div><Field label="Bio"><Textarea value={form.bio} onChange={(event) => setForm({ ...form, bio: event.target.value })} /></Field></CardContent></Card>
    <Card><CardHeader><h2 className="font-display text-xl font-semibold">Contas vinculadas</h2><p className="mt-1 text-sm text-arena-muted">IDs e perfis usados na sua identidade competitiva.</p></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{linkFields.map(([key, label]) => <Field label={label} key={key}><Input value={form.links[key]} onChange={(event) => setForm({ ...form, links: { ...form.links, [key]: event.target.value } })} /></Field>)}</div><Button className="mt-5" loading={busy === "profile"} icon={<Check className="h-4 w-4" />} onClick={() => void saveProfile()}>Salvar perfil e contas</Button></CardContent></Card>
    <Card><CardHeader><h2 className="font-display text-xl font-semibold">Meus jogos</h2><p className="mt-1 text-sm text-arena-muted">Vincule o ID oficial usado em cada jogo.</p></CardHeader><CardContent className="grid gap-4 xl:grid-cols-2">{data.games.map((game) => { const value = gameForms[game.game_id]; return <div className="border border-arena-line p-4" key={game.game_id}><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-3"><Gamepad2 className="h-5 w-5 text-cyan-200" /><div><p className="font-semibold">{game.nome}</p><p className="text-xs text-arena-muted">{game.selected ? "Vinculado" : "Nao vinculado"}</p></div></div><StatusBadge value={game.selected ? "ativo" : "pendente"} /></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Nickname no jogo"><Input value={value.nickname} onChange={(event) => setGameForms({ ...gameForms, [game.game_id]: { ...value, nickname: event.target.value } })} /></Field><Field label="ID da plataforma"><Input value={value.game_player_id} onChange={(event) => setGameForms({ ...gameForms, [game.game_id]: { ...value, game_player_id: event.target.value } })} /></Field><Field label="Rank"><Input value={value.rank_name} onChange={(event) => setGameForms({ ...gameForms, [game.game_id]: { ...value, rank_name: event.target.value } })} /></Field><Field label="Elo"><Input min="0" type="number" value={value.elo} onChange={(event) => setGameForms({ ...gameForms, [game.game_id]: { ...value, elo: event.target.value } })} /></Field></div><Button className="mt-4 w-full" loading={busy === `game-${game.game_id}`} onClick={() => void saveGame(game)}>{game.selected ? "Atualizar jogo" : "Vincular jogo"}</Button></div>; })}</CardContent></Card>
  </div>;
}

export function PlayerTeamsModule({ data, busy, run }: PlayerModuleProps) {
  const [filters, setFilters] = useState({ query: "", game_id: "", region: "", recruiting: true });
  const [results, setResults] = useState<PlayerTeamSearchResult[]>(data.recommended_teams);
  const [requestTeam, setRequestTeam] = useState<PlayerTeamSearchResult | null>(null);
  const [message, setMessage] = useState("");
  const [leaveOpen, setLeaveOpen] = useState(false);
  const [leaveName, setLeaveName] = useState("");
  const invitations = data.requests.filter((item) => item.tipo === "invite" && item.status === "pending");
  const sent = data.requests.filter((item) => item.tipo === "request" && item.status === "pending");
  async function search() {
    await run("team-search", async () => setResults(await searchPlayerTeams({ ...filters, game_id: filters.game_id ? Number(filters.game_id) : null })), "Busca atualizada", false);
  }
  async function sendRequest() {
    if (!requestTeam) return;
    const ok = await run(`request-${requestTeam.id}`, () => requestPlayerTeam(requestTeam.id, message), "Solicitacao enviada");
    if (ok) { setRequestTeam(null); setMessage(""); }
  }
  return <div className="space-y-5">
    {data.current_team ? <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-xl font-semibold">{data.current_team.team_name}</h2><p className="mt-1 text-sm text-arena-muted">{data.current_team.game_name} · {data.current_team.team_region || "Regiao nao informada"}</p></div><Link to={`/equipe/${data.current_team.team_slug}`}><Button variant="secondary" icon={<Shield className="h-4 w-4" />}>Perfil publico</Button></Link></div></CardHeader><CardContent><div className="grid gap-4 lg:grid-cols-[.7fr_1.3fr]"><div className="grid grid-cols-2 gap-3"><Metric label="Ranking interno" value={data.team_ranking.players.find((item) => item.user_id === data.profile.id)?.position ? `#${data.team_ranking.players.find((item) => item.user_id === data.profile.id)?.position}` : "-"} /><Metric label="Elenco" value={String(data.members.length)} /><Metric label="Funcao" value={roleLabel(data.current_team.cargo)} /><Metric label="Lineup" value={data.current_team.lineup_status} /></div><div className="space-y-2">{data.members.map((member) => <div className="flex items-center justify-between border-b border-arena-line py-2" key={member.id}><div><p className="text-sm font-semibold">{member.nick || member.nickname || member.nome}</p><p className="text-xs text-arena-muted">ID #{member.player_id ?? "-"} · {member.game_uid || "ID do jogo pendente"}</p></div><div className="flex gap-2"><Badge tone={member.lineup_status === "titular" ? "success" : "info"}>{member.lineup_status}</Badge><Badge>{roleLabel(member.cargo)}</Badge></div></div>)}</div></div></CardContent></Card> : null}
    <div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><h2 className="font-display text-xl font-semibold">Convites recebidos</h2></CardHeader><CardContent className="space-y-3">{invitations.map((invite) => <div className="border border-arena-line p-4" key={invite.id}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{invite.team_name}</p><p className="text-sm text-arena-muted">{invite.game_name} · convite de {invite.invited_by_name || "Lider da equipe"}</p></div><StatusBadge value={invite.status} /></div>{invite.message ? <p className="mt-3 border-l-2 border-cyan-400 pl-3 text-sm text-arena-muted">{invite.message}</p> : null}<div className="mt-4 flex flex-wrap gap-2"><Button loading={busy === `invite-${invite.id}`} icon={<Check className="h-4 w-4" />} onClick={() => void run(`invite-${invite.id}`, () => respondPlayerInvite(invite.id, "accept"), "Convite aceito")}>Aceitar</Button><Button variant="secondary" icon={<X className="h-4 w-4" />} onClick={() => void run(`reject-${invite.id}`, () => respondPlayerInvite(invite.id, "reject"), "Convite recusado")}>Recusar</Button><Button variant="danger" icon={<XCircle className="h-4 w-4" />} onClick={() => confirmAction("Recusar e bloquear futuros convites desta equipe?", () => void run(`block-${invite.id}`, () => respondPlayerInvite(invite.id, "block"), "Equipe bloqueada"))}>Bloquear</Button></div></div>)}{!invitations.length ? <InlineEmpty text="Nenhum convite aguardando sua resposta." /> : null}</CardContent></Card><Card><CardHeader><h2 className="font-display text-xl font-semibold">Minhas solicitacoes</h2></CardHeader><CardContent className="space-y-3">{sent.map((request) => <div className="flex items-center justify-between gap-3 border border-arena-line p-4" key={request.id}><div><p className="font-semibold">{request.team_name}</p><p className="text-sm text-arena-muted">{request.game_name} · enviada em {formatDate(request.created_at)}</p></div><Button variant="danger" loading={busy === `cancel-${request.id}`} onClick={() => void run(`cancel-${request.id}`, () => cancelPlayerTeamRequest(request.id), "Solicitacao cancelada")}>Cancelar</Button></div>)}{!sent.length ? <InlineEmpty text="Nenhuma solicitacao pendente." /> : null}</CardContent></Card></div>
    <Card><CardHeader><h2 className="font-display text-xl font-semibold">Encontrar equipe</h2><p className="mt-1 text-sm text-arena-muted">Procure por jogo, regiao e recrutamento aberto.</p></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-4"><Input placeholder="Nome ou tag" value={filters.query} onChange={(event) => setFilters({ ...filters, query: event.target.value })} /><Select value={filters.game_id} onChange={(event) => setFilters({ ...filters, game_id: event.target.value })}><option value="">Todos os jogos</option>{data.games.map((game) => <option key={game.game_id} value={game.game_id}>{game.nome}</option>)}</Select><Input placeholder="Regiao" value={filters.region} onChange={(event) => setFilters({ ...filters, region: event.target.value })} /><Button loading={busy === "team-search"} icon={<Search className="h-4 w-4" />} onClick={() => void search()}>Pesquisar</Button></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{results.map((team) => <div className="border border-arena-line p-4" key={team.id}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{team.nome} {team.tag ? `[${team.tag}]` : ""}</p><p className="text-xs text-arena-muted">{team.game_name} · {team.regiao || "Regiao aberta"}</p></div><Badge tone={team.recruiting ? "success" : "neutral"}>{team.recruiting ? "Recrutando" : "Fechada"}</Badge></div><p className="mt-3 line-clamp-2 min-h-10 text-sm text-arena-muted">{team.descricao || "Equipe competitiva da Arena Camp."}</p><div className="mt-4 flex items-center justify-between"><span className="text-xs text-arena-muted">{team.member_count} membros</span><Button className="h-9" disabled={!team.recruiting || Boolean(team.pending_request_id)} icon={<Send className="h-4 w-4" />} onClick={() => setRequestTeam(team)}>{team.pending_request_id ? "Solicitado" : "Solicitar entrada"}</Button></div></div>)}{!results.length ? <div className="md:col-span-2 xl:col-span-3"><InlineEmpty text="Nenhuma equipe encontrada com estes filtros." /></div> : null}</div></CardContent></Card>
    {data.current_team && data.current_team.cargo === "player" ? <Card><CardHeader><h2 className="font-display text-xl font-semibold text-red-300">Sair da equipe</h2><p className="mt-1 text-sm text-arena-muted">Seu historico competitivo sera preservado. O lider e o capitao serao avisados.</p></CardHeader><CardContent><Button variant="danger" icon={<LogOut className="h-4 w-4" />} onClick={() => setLeaveOpen(true)}>Solicitar saida</Button></CardContent></Card> : null}
    <Modal open={Boolean(requestTeam)} title="Solicitar entrada" description={requestTeam ? `${requestTeam.nome} · ${requestTeam.game_name}` : undefined} onClose={() => setRequestTeam(null)}><div className="space-y-4"><Field label="Mensagem para o lider"><Textarea placeholder="Conte sobre sua funcao, experiencia e disponibilidade." value={message} onChange={(event) => setMessage(event.target.value)} /></Field><Button className="w-full" loading={busy === `request-${requestTeam?.id}`} icon={<Send className="h-4 w-4" />} onClick={() => void sendRequest()}>Enviar solicitacao</Button></div></Modal>
    <Modal open={leaveOpen} title="Sair da equipe" description="Esta acao remove voce do elenco ativo, mas mantem estatisticas e historico." onClose={() => setLeaveOpen(false)}><div className="space-y-4"><Field label={`Digite ${data.current_team?.team_name || "o nome da equipe"}`}><Input value={leaveName} onChange={(event) => setLeaveName(event.target.value)} /></Field><Button className="w-full" variant="danger" disabled={leaveName !== data.current_team?.team_name} loading={busy === "leave-team"} onClick={() => void run("leave-team", () => leavePlayerWorkspaceTeam(leaveName, data.current_team?.team_id), "Voce saiu da equipe").then((ok) => { if (ok) setLeaveOpen(false); })}>Confirmar saida</Button></div></Modal>
  </div>;
}

function profileForm(profile: PlayerWorkspaceProfile) {
  return { nome: profile.nome || "", nickname: profile.nickname || "", avatar: profile.avatar || "", banner: profile.banner || "", bio: profile.bio || "", cidade: profile.cidade || "", estado: profile.estado || "", pais: profile.pais || "", birth_date: profile.birth_date ? String(profile.birth_date).slice(0, 10) : "", languages: profile.languages.join(", "), links: Object.fromEntries(Object.entries(profile.links).map(([key, value]) => [key, value || ""])) as Record<keyof PlayerWorkspaceProfile["links"], string> };
}

function gameForm(game: PlayerWorkspaceGame) {
  return { nickname: game.nickname || "", game_player_id: game.game_player_id || "", rank_name: game.rank_name || "", elo: game.elo === null ? "" : String(game.elo), level: game.level === null ? "" : String(game.level) };
}
