import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CreditCard, Shuffle, TicketCheck } from "lucide-react";
import { Badge } from "../../components/ui/Badge";
import { Button } from "../../components/ui/Button";
import { Card, CardContent, CardHeader } from "../../components/ui/Card";
import { cancelMixTournamentRegistration, createMixTournamentPayment, getMixTournaments, registerMixTournament } from "../../services/api";
import { useToast } from "../../hooks/useToast";
import type { MixTournament } from "../../types/api";

export function PlayerMixModule(){const toast=useToast(),client=useQueryClient();const{data=[],isLoading}=useQuery({queryKey:["mix-tournaments"],queryFn:getMixTournaments});async function run(action:()=>Promise<unknown>,message:string){try{await action();toast.success(message);await client.invalidateQueries({queryKey:["mix-tournaments"]});}catch(error){toast.error("Operação não concluida",error instanceof Error?error.message:"Tente novamente.");}}
 return <Card><CardHeader><h2 className="font-display text-xl font-semibold">Torneios Mix</h2><p className="text-sm text-arena-muted">Inscreva-se individualmente. As equipes e os mapas sao sorteados pelo sistema.</p></CardHeader><CardContent className="space-y-3">{isLoading?<p className="py-8 text-center text-sm text-arena-muted">Carregando torneios Mix.</p>:null}{!isLoading&&!data.length?<p className="py-8 text-center text-sm text-arena-muted">Nenhum Mix disponivel no momento.</p>:null}{data.map(item=><MixItem item={item} key={item.tournament_id} run={run}/>)}</CardContent></Card>;
}
function MixItem({item,run}:{item:MixTournament;run:(action:()=>Promise<unknown>,message:string)=>Promise<void>}){const registered=Boolean(item.registration_id),hasPix=Boolean(item.qr_code_base64||item.copia_cola);return <div className="border border-arena-line bg-black/20 p-4"><div className="grid gap-4 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{item.nome}</h3><Badge tone={item.payment_mode==="free"?"success":"info"}>{item.payment_mode==="free"?"Gratuito":money(item.price_per_player)}</Badge>{item.registration_status?<Badge tone={item.payment_status==="paid"||item.payment_status==="free"?"success":"warning"}>{status(item.registration_status,item.payment_status)}</Badge>:null}</div><p className="mt-2 text-sm text-arena-muted">{item.team_count} equipes de {item.players_per_team} jogadores · {item.registered_players}/{item.max_players} inscritos</p></div><div className="flex flex-wrap gap-2">{!registered?<Button icon={<TicketCheck className="h-4 w-4"/>} onClick={()=>void run(()=>registerMixTournament(item.tournament_id),"Inscrição realizada")}>Participar</Button>:null}{registered&&item.payment_mode==="paid"&&item.payment_status==="pending"&&!hasPix?<Button icon={<CreditCard className="h-4 w-4"/>} onClick={()=>void run(()=>createMixTournamentPayment(item.tournament_id),"PIX gerado")}>Gerar PIX</Button>:null}{registered&&item.draw_status==="pending"?<Button variant="secondary" onClick={()=>void run(()=>cancelMixTournamentRegistration(item.tournament_id),"Inscrição cancelada")}>Cancelar</Button>:null}{item.draw_status==="completed"?<Badge tone="info"><Shuffle className="mr-1 h-3 w-3"/>Sorteio realizado</Badge>:null}</div></div>{hasPix&&item.payment_status==="pending"?<div className="mt-4 grid gap-4 border-t border-arena-line pt-4 md:grid-cols-[180px_1fr]">{item.qr_code_base64?<img className="h-44 w-44 bg-white p-2" src={item.qr_code_base64.startsWith("data:")?item.qr_code_base64:`data:image/png;base64,${item.qr_code_base64}`} alt="QR Code PIX"/>:null}<div><p className="font-semibold">PIX da inscrição</p><p className="mt-1 text-sm text-arena-muted">A confirmação será automatica apos o pagamento.</p>{item.copia_cola?<textarea className="mt-3 min-h-24 w-full border border-arena-line bg-black/30 p-3 text-xs" readOnly value={item.copia_cola}/>:null}</div></div>:null}</div>}
function money(value:number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(value));}function status(registration:string,payment:string|null|undefined){if(registration==="assigned")return"Equipe sorteada";if(registration==="waitlist")return"Lista de espera";if(payment==="pending")return"Aguardando pagamento";return"Confirmado";}
