import { Bell, KeyRound, Lock, LogOut, MessageSquare, Paperclip, Save, Send, ShieldCheck, TicketCheck } from "lucide-react";
import { useState } from "react";
import { Badge } from "../../components/ui/Badge";
import { Button } from "../../components/ui/Button";
import { Card, CardContent, CardHeader } from "../../components/ui/Card";
import { EmptyState } from "../../components/ui/EmptyState";
import { Input, Select } from "../../components/ui/Form";
import { useAuth } from "../../contexts/AuthContext";
import {
  changePlayerWorkspacePassword,
  createPlayerSupportTicket,
  replyPlayerSupportTicket,
  sendPlayerWorkspaceTeamMessage,
  updatePlayerWorkspaceSettings
} from "../../services/api";
import { Field, InlineEmpty, StatusBadge, Textarea, formatDate, type PlayerModuleProps } from "./playerWorkspaceShared";

export function PlayerMessagesModule({ data, busy, run }: PlayerModuleProps) {
  const [message, setMessage] = useState("");
  const [attachment, setAttachment] = useState("");
  async function send() {
    const ok = await run("team-message", () => sendPlayerWorkspaceTeamMessage({ message, attachment_url: attachment || null, team_id: data.current_team?.team_id }), "Mensagem enviada");
    if (ok) { setMessage(""); setAttachment(""); }
  }
  if (!data.current_team) return <EmptyState title="Chat indisponivel" description="Voce precisa estar em uma equipe para acessar a comunicacao interna." />;
  return <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]">
    <Card><CardHeader><div className="flex items-center gap-3"><MessageSquare className="h-5 w-5 text-cyan-200" /><div><h2 className="font-display text-xl font-semibold">Chat da equipe</h2><p className="text-sm text-arena-muted">Canal interno de {data.current_team.team_name}.</p></div></div></CardHeader><CardContent><div className="max-h-[520px] space-y-3 overflow-y-auto pr-2 scrollbar-thin">{data.messages.team.map((item) => <div className={`max-w-[88%] border p-3 ${item.user_id === data.profile.id ? "ml-auto border-cyan-400/40 bg-cyan-400/10" : "border-arena-line bg-white/[.03]"}`} key={item.id}><div className="flex items-center justify-between gap-4"><p className="text-sm font-semibold">{item.nickname || item.nome}</p><p className="text-xs text-arena-muted">{formatDate(item.created_at)}</p></div><p className="mt-2 whitespace-pre-wrap text-sm text-arena-text">{item.message}</p>{item.attachment_url ? <a className="mt-2 inline-flex items-center gap-2 text-xs text-cyan-200 hover:underline" href={item.attachment_url} rel="noreferrer" target="_blank"><Paperclip className="h-3 w-3" /> Abrir anexo</a> : null}</div>)}{!data.messages.team.length ? <InlineEmpty text="Nenhuma mensagem enviada ainda." /> : null}</div><div className="mt-5 space-y-3 border-t border-arena-line pt-4"><Textarea placeholder="Escreva para sua equipe..." value={message} onChange={(event) => setMessage(event.target.value)} /><div className="flex flex-col gap-3 sm:flex-row"><Input placeholder="URL de anexo (opcional)" value={attachment} onChange={(event) => setAttachment(event.target.value)} /><Button loading={busy === "team-message"} disabled={!message.trim()} icon={<Send className="h-4 w-4" />} onClick={() => void send()}>Enviar</Button></div></div></CardContent></Card>
    <Card><CardHeader><div className="flex items-center gap-3"><Bell className="h-5 w-5 text-cyan-200" /><h2 className="font-display text-xl font-semibold">Central de avisos</h2></div></CardHeader><CardContent className="space-y-3">{data.notifications.map((item) => <div className={`border-l-2 p-3 ${item.lida ? "border-arena-line bg-white/[.02]" : "border-cyan-400 bg-cyan-400/[.06]"}`} key={item.id}><div className="flex items-start justify-between gap-2"><p className="text-sm font-semibold">{item.titulo}</p>{!item.lida ? <span className="mt-1 h-2 w-2 shrink-0 bg-cyan-300" /> : null}</div><p className="mt-1 text-sm text-arena-muted">{item.mensagem}</p><p className="mt-2 text-xs text-arena-muted">{formatDate(item.created_at)}</p></div>)}{!data.notifications.length ? <InlineEmpty text="Nenhum aviso recebido." /> : null}</CardContent></Card>
  </div>;
}

export function PlayerSupportModule({ data, busy, run }: PlayerModuleProps) {
  const [form, setForm] = useState({ category: "geral", priority: "media", subject: "", message: "" });
  const [replies, setReplies] = useState<Record<number, string>>({});
  async function create() {
    const ok = await run("new-ticket", () => createPlayerSupportTicket(form), "Chamado aberto");
    if (ok) setForm({ category: "geral", priority: "media", subject: "", message: "" });
  }
  async function reply(ticketId: number) {
    const ok = await run(`reply-${ticketId}`, () => replyPlayerSupportTicket(ticketId, replies[ticketId] || ""), "Resposta adicionada");
    if (ok) setReplies({ ...replies, [ticketId]: "" });
  }
  return <div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]">
    <Card><CardHeader><div className="flex items-center gap-3"><TicketCheck className="h-5 w-5 text-cyan-200" /><div><h2 className="font-display text-xl font-semibold">Abrir chamado</h2><p className="text-sm text-arena-muted">Fale com a administracao da Arena Camp.</p></div></div></CardHeader><CardContent className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Categoria"><Select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}><option value="geral">Geral</option><option value="conta">Conta</option><option value="equipe">Equipe</option><option value="partida">Partida</option><option value="estatisticas">Estatisticas</option><option value="seguranca">Seguranca</option></Select></Field><Field label="Prioridade"><Select value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })}><option value="baixa">Baixa</option><option value="media">Media</option><option value="alta">Alta</option><option value="critica">Critica</option></Select></Field></div><Field label="Assunto"><Input value={form.subject} onChange={(event) => setForm({ ...form, subject: event.target.value })} /></Field><Field label="Mensagem"><Textarea value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} /></Field><Button className="w-full" loading={busy === "new-ticket"} disabled={!form.subject.trim() || !form.message.trim()} icon={<Send className="h-4 w-4" />} onClick={() => void create()}>Abrir chamado</Button></CardContent></Card>
    <Card><CardHeader><h2 className="font-display text-xl font-semibold">Meus chamados</h2></CardHeader><CardContent className="space-y-4">{data.tickets.map((ticket) => <div className="border border-arena-line" key={ticket.id}><div className="flex flex-wrap items-start justify-between gap-3 border-b border-arena-line bg-white/[.03] p-4"><div><p className="font-semibold">#{ticket.id} · {ticket.subject}</p><p className="mt-1 text-xs text-arena-muted">{ticket.category} · {formatDate(ticket.created_at)}</p></div><div className="flex gap-2"><Badge>{ticket.priority}</Badge><StatusBadge value={ticket.status} /></div></div><div className="space-y-3 p-4"><div className="border-l-2 border-cyan-400 pl-3"><p className="text-xs font-semibold uppercase text-arena-muted">Mensagem inicial</p><p className="mt-1 whitespace-pre-wrap text-sm">{ticket.message}</p></div>{ticket.response ? <div className="border-l-2 border-emerald-400 pl-3"><p className="text-xs font-semibold uppercase text-arena-muted">Resposta da administracao</p><p className="mt-1 whitespace-pre-wrap text-sm">{ticket.response}</p></div> : null}{ticket.messages.map((reply) => <div className={`border-l-2 pl-3 ${reply.user_id === data.profile.id ? "border-cyan-400" : "border-emerald-400"}`} key={reply.id}><p className="text-xs font-semibold uppercase text-arena-muted">{reply.nome} · {formatDate(reply.created_at)}</p><p className="mt-1 whitespace-pre-wrap text-sm">{reply.message}</p></div>)}{ticket.status !== "fechado" ? <div className="flex flex-col gap-2 border-t border-arena-line pt-3 sm:flex-row"><Input placeholder="Adicionar resposta" value={replies[ticket.id] || ""} onChange={(event) => setReplies({ ...replies, [ticket.id]: event.target.value })} /><Button loading={busy === `reply-${ticket.id}`} disabled={!replies[ticket.id]?.trim()} onClick={() => void reply(ticket.id)}>Responder</Button></div> : null}</div></div>)}{!data.tickets.length ? <InlineEmpty text="Voce ainda nao abriu nenhum chamado." /> : null}</CardContent></Card>
  </div>;
}

export function PlayerSettingsModule({ data, busy, run }: PlayerModuleProps) {
  const { logout } = useAuth();
  const [preferences, setPreferences] = useState({ ...data.profile.preferences });
  const [password, setPassword] = useState({ current_password: "", new_password: "", confirm_password: "" });
  async function savePreferences() { await run("preferences", () => updatePlayerWorkspaceSettings(preferences), "Preferencias atualizadas"); }
  async function savePassword() {
    const ok = await run("password", () => changePlayerWorkspacePassword(password), "Senha alterada", false);
    if (ok) setPassword({ current_password: "", new_password: "", confirm_password: "" });
  }
  return <div className="grid gap-5 xl:grid-cols-2">
    <Card><CardHeader><div className="flex items-center gap-3"><Save className="h-5 w-5 text-cyan-200" /><div><h2 className="font-display text-xl font-semibold">Preferencias</h2><p className="text-sm text-arena-muted">Tema, idioma, privacidade e notificacoes.</p></div></div></CardHeader><CardContent className="space-y-4"><Field label="Tema"><Select value={preferences.theme} onChange={(event) => setPreferences({ ...preferences, theme: event.target.value as typeof preferences.theme })}><option value="dark">Escuro</option><option value="light">Claro</option><option value="system">Usar configuracao do sistema</option></Select></Field><Field label="Idioma"><Select value={preferences.language} onChange={(event) => setPreferences({ ...preferences, language: event.target.value })}><option value="pt-BR">Portugues (Brasil)</option><option value="en-US">English</option><option value="es-ES">Espanol</option></Select></Field><Toggle label="Perfil publico" description="Permitir que outros usuarios consultem sua carreira." checked={preferences.profile_public} onChange={(value) => setPreferences({ ...preferences, profile_public: value })} /><Toggle label="Notificacoes por e-mail" description="Receber avisos importantes no e-mail cadastrado." checked={preferences.email_notifications} onChange={(value) => setPreferences({ ...preferences, email_notifications: value })} /><Toggle label="Notificacoes no Discord" description="Receber integracoes quando houver um Discord vinculado." checked={preferences.discord_notifications} onChange={(value) => setPreferences({ ...preferences, discord_notifications: value })} /><Button loading={busy === "preferences"} icon={<Save className="h-4 w-4" />} onClick={() => void savePreferences()}>Salvar preferencias</Button></CardContent></Card>
    <div className="space-y-5"><Card><CardHeader><div className="flex items-center gap-3"><KeyRound className="h-5 w-5 text-cyan-200" /><div><h2 className="font-display text-xl font-semibold">Alterar senha</h2><p className="text-sm text-arena-muted">Use pelo menos oito caracteres.</p></div></div></CardHeader><CardContent className="space-y-4"><Field label="Senha atual"><Input autoComplete="current-password" type="password" value={password.current_password} onChange={(event) => setPassword({ ...password, current_password: event.target.value })} /></Field><Field label="Nova senha"><Input autoComplete="new-password" type="password" value={password.new_password} onChange={(event) => setPassword({ ...password, new_password: event.target.value })} /></Field><Field label="Confirmar nova senha"><Input autoComplete="new-password" type="password" value={password.confirm_password} onChange={(event) => setPassword({ ...password, confirm_password: event.target.value })} /></Field><Button loading={busy === "password"} disabled={password.new_password.length < 8 || password.new_password !== password.confirm_password} icon={<Lock className="h-4 w-4" />} onClick={() => void savePassword()}>Atualizar senha</Button></CardContent></Card><Card><CardHeader><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-cyan-200" /><div><h2 className="font-display text-xl font-semibold">Sessao atual</h2><p className="text-sm text-arena-muted">Este navegador esta autenticado com token protegido.</p></div></div></CardHeader><CardContent><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="font-semibold">Navegador atual</p><p className="text-sm text-arena-muted">{navigator.userAgent.includes("Chrome") ? "Chrome" : "Navegador web"} · sessao ativa</p></div><Button variant="danger" icon={<LogOut className="h-4 w-4" />} onClick={logout}>Encerrar sessao</Button></div></CardContent></Card></div>
  </div>;
}

function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void }) {
  return <label className="flex cursor-pointer items-center justify-between gap-4 border border-arena-line p-3"><span><span className="block text-sm font-semibold">{label}</span><span className="block text-xs text-arena-muted">{description}</span></span><input className="h-4 w-4 accent-cyan-400" type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /></label>;
}
