import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Shuffle, Users } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { Badge } from "../components/ui/Badge";
import { Button } from "../components/ui/Button";
import { Card, CardContent, CardHeader } from "../components/ui/Card";
import { PageHeader } from "../components/ui/PageHeader";
import { drawAdminMixTournament, getAdminMixTournament, updateAdminMixRegistration } from "../services/api";
import { useToast } from "../hooks/useToast";

export function AdminMixTournamentPage(){const id=Number(useParams().id),toast=useToast(),client=useQueryClient();const{data,isLoading}=useQuery({queryKey:["admin-mix",id],queryFn:()=>getAdminMixTournament(id),enabled:Number.isInteger(id)});async function draw(){if(!window.confirm("Confirmar o sorteio definitivo das equipes e do chaveamento?"))return;try{await drawAdminMixTournament(id);toast.success("Sorteio concluido","Equipes, mapas e primeira rodada foram gerados.");await client.invalidateQueries({queryKey:["admin-mix",id]});}catch(error){toast.error("Sorteio não realizado",error instanceof Error?error.message:"Tente novamente.");}}
 async function updateRegistration(registrationId:number,status:"confirmed"|"cancelled"|"waitlist"){try{await updateAdminMixRegistration(id,registrationId,status);toast.success("Inscrição atualizada");await client.invalidateQueries({queryKey:["admin-mix",id]});}catch(error){toast.error("Operação não concluida",error instanceof Error?error.message:"Tente novamente.");}}
 if(isLoading||!data)return <p className="p-8 text-arena-muted">Carregando central do Mix.</p>;const ready=Number(data.confirmed_players)===Number(data.max_players)&&data.draw_status==="pending";return <section className="px-4 pb-12 lg:px-8"><PageHeader eyebrow="Mix Individual" title={data.nome} description={`${data.team_count} equipes de ${data.players_per_team} jogadores · eliminacao simples MD1`} action={<Link to="/admin?module=competitions"><Button variant="secondary" icon={<ArrowLeft className="h-4 w-4"/>}>Competicoes</Button></Link>}/><div className="grid gap-4 md:grid-cols-3"><Metric label="Inscritos" value={`${data.registered_players}/${data.max_players}`}/><Metric label="Confirmados" value={`${data.confirmed_players}/${data.max_players}`}/><Metric label="Inscrição" value={data.payment_mode==="free"?"Gratuita":money(data.price_per_player)}/></div><Card className="mt-5"><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-xl font-semibold">Participantes</h2><p className="text-sm text-arena-muted">Somente confirmados entram no sorteio.</p></div><Button disabled={!ready} icon={<Shuffle className="h-4 w-4"/>} onClick={()=>void draw()}>Sortear equipes</Button></div></CardHeader><CardContent className="space-y-2">{!data.registrations?.length?<p className="py-8 text-center text-sm text-arena-muted">Nenhum jogador inscrito.</p>:data.registrations.map(item=><div className="grid gap-2 border border-arena-line bg-black/20 p-3 lg:grid-cols-[1fr_auto_auto_auto] lg:items-center" key={item.id}><span className="font-semibold">{item.nickname||item.nome}</span><Badge tone={item.payment_status==="paid"||item.payment_status==="free"?"success":"warning"}>{item.payment_status}</Badge><Badge tone={item.status==="assigned"||item.status==="confirmed"?"success":"info"}>{item.status}</Badge>{data.draw_status==="pending"?<div className="flex gap-2">{item.status!=="confirmed"?<Button className="h-8" onClick={()=>void updateRegistration(item.id,"confirmed")}>Confirmar</Button>:null}<Button className="h-8" variant="secondary" onClick={()=>void updateRegistration(item.id,"waitlist")}>Espera</Button><Button className="h-8" variant="danger" onClick={()=>void updateRegistration(item.id,"cancelled")}>Cancelar</Button></div>:null}</div>)}</CardContent></Card>{data.teams?.length?<Card className="mt-5"><CardHeader><h2 className="font-display text-xl font-semibold">Equipes sorteadas</h2></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{data.teams.map(team=><div className="border border-arena-line p-4" key={team.team_id} style={{borderLeftColor:team.color_hex,borderLeftWidth:4}}><p className="font-semibold">{team.nome}</p><p className="mt-1 text-xs text-arena-muted">Seed #{team.seed_number}</p></div>)}</CardContent></Card>:null}</section>}
function Metric({label,value}:{label:string;value:string}){return <div className="border border-arena-line bg-black/20 p-4"><Users className="h-5 w-5 text-cyan-200"/><p className="mt-3 text-xs uppercase text-arena-muted">{label}</p><p className="mt-1 font-display text-2xl font-bold">{value}</p></div>}function money(value:number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(value));}
