import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ExternalLink, Radio, Trophy } from "lucide-react";
import { Badge } from "../components/ui/Badge";
import { Card, CardContent } from "../components/ui/Card";
import { EmptyState } from "../components/ui/EmptyState";
import { PageHeader } from "../components/ui/PageHeader";
import { getOfficialTournament, getOfficialTournaments } from "../services/api";

export function OfficialTournamentsPage() {
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const { data: events = [], isLoading } = useQuery({ queryKey: ["official-tournaments"], queryFn: getOfficialTournaments });
  const { data: selected } = useQuery({ queryKey: ["official-tournament", selectedId], queryFn: () => getOfficialTournament(Number(selectedId)), enabled: Boolean(selectedId) });
  return <section className="px-4 pb-16 lg:px-8">
    <PageHeader eyebrow="Circuito mundial" title="Campeonatos oficiais" description="Agenda, transmissao e resultados de eventos como BLAST, IEM e outros circuitos acompanhados pela Arena Camp." />
    {isLoading ? <EmptyState title="Carregando circuito" description="Consultando os campeonatos publicados." /> : null}
    {!isLoading && !events.length ? <EmptyState title="Nenhum campeonato publicado" description="Os proximos eventos oficiais aparecerao aqui." /> : null}
    <div className="grid gap-5 lg:grid-cols-2 xl:grid-cols-3">{events.map((event) => <button className="group overflow-hidden border border-arena-line bg-arena-panel text-left transition hover:border-cyan-400/50" key={event.id} onClick={() => setSelectedId(event.id)}>
      <div className="relative aspect-[16/7] overflow-hidden bg-[#071321]">{event.banner_url ? <img className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.03]" src={event.banner_url} alt="" /> : <div className="flex h-full items-center justify-center"><Trophy className="h-12 w-12 text-cyan-200" /></div>}<Badge className="absolute right-3 top-3" tone={event.status === "em_andamento" ? "danger" : event.status === "finalizado" ? "success" : "info"}>{label(event.status)}</Badge></div>
      <div className="p-5"><div className="flex items-center gap-3">{event.logo_url ? <img className="h-12 w-12 object-contain" src={event.logo_url} alt="" /> : null}<div><p className="text-xs font-semibold uppercase text-cyan-200">{event.organizer} · {event.game_name}</p><h2 className="mt-1 font-display text-xl font-bold">{event.name}</h2></div></div><div className="mt-5 grid grid-cols-3 gap-3 border-t border-arena-line pt-4 text-sm"><Metric title="Formato" value={event.format_label || "A definir"} /><Metric title="Premiacao" value={event.prize_pool || "A definir"} /><Metric title="Partidas" value={String(event.matches_count || 0)} /></div></div>
    </button>)}</div>
    {selected ? <div className="fixed inset-0 z-50 overflow-y-auto bg-black/80 p-4 backdrop-blur-sm" onMouseDown={(event) => { if (event.currentTarget === event.target) setSelectedId(null); }}><Card className="mx-auto my-8 max-w-5xl overflow-hidden"><div className="relative min-h-48 bg-[#071321]">{selected.banner_url ? <img className="absolute inset-0 h-full w-full object-cover opacity-55" src={selected.banner_url} alt="" /> : null}<div className="relative p-7"><button className="absolute right-5 top-4 text-2xl text-white" onClick={() => setSelectedId(null)} aria-label="Fechar">×</button><p className="text-xs font-semibold uppercase text-cyan-200">{selected.organizer} · {selected.game_name}</p><h2 className="mt-2 max-w-3xl font-display text-3xl font-bold">{selected.name}</h2><p className="mt-3 max-w-2xl text-sm text-slate-200">{selected.description}</p></div></div><CardContent className="space-y-5">
      <div className="flex flex-wrap items-center gap-4 text-sm text-arena-muted"><Badge tone={selected.status === "em_andamento" ? "danger" : "info"}>{label(selected.status)}</Badge><span>{selected.location || "Local a definir"}</span><span>{selected.format_label || "Formato a definir"}</span><span>{selected.prize_pool || "Premiacao a definir"}</span>{selected.official_url ? <a className="inline-flex items-center gap-2 text-cyan-200" href={selected.official_url} target="_blank" rel="noreferrer"><ExternalLink className="h-4 w-4" />Site oficial</a> : null}</div>
      <div><h3 className="font-display text-xl font-semibold">Agenda e resultados</h3><div className="mt-3 space-y-2">{selected.matches?.map((match) => <div className="grid items-center gap-3 border border-arena-line p-4 md:grid-cols-[140px_1fr_auto]" key={match.id}><div><Badge tone={match.status === "ao_vivo" ? "danger" : match.status === "finalizada" ? "success" : "neutral"}>{label(match.status)}</Badge><p className="mt-2 text-xs text-arena-muted">{match.stage_label || "Fase a definir"} · {match.best_of.toUpperCase()}</p></div><div className="text-center font-semibold"><span className={match.winner_name === match.team_a ? "text-emerald-300" : ""}>{match.team_a}</span><strong className="mx-4 text-xl">{match.score_a ?? "-"} x {match.score_b ?? "-"}</strong><span className={match.winner_name === match.team_b ? "text-emerald-300" : ""}>{match.team_b}</span>{match.map_summary ? <p className="mt-1 text-xs font-normal text-arena-muted">{match.map_summary}</p> : null}</div>{match.stream_url ? <a className="inline-flex items-center gap-2 text-sm text-cyan-200" href={match.stream_url} target="_blank" rel="noreferrer"><Radio className="h-4 w-4" />Assistir</a> : <span />}</div>)}{!selected.matches?.length ? <EmptyState title="Agenda ainda nao publicada" description="As partidas aparecerao assim que forem confirmadas." /> : null}</div></div>
    </CardContent></Card></div> : null}
  </section>;
}
function Metric({ title, value }: { title: string; value: string }) { return <div><p className="text-xs text-arena-muted">{title}</p><p className="mt-1 truncate font-semibold">{value}</p></div>; }
function label(value: string) { return ({ anunciado: "Anunciado", em_andamento: "Ao vivo", finalizado: "Finalizado", cancelado: "Cancelado", agendada: "Agendada", ao_vivo: "Ao vivo", finalizada: "Finalizada" } as Record<string, string>)[value] || value; }
